# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='date_of_inc',
            field=models.CharField(max_length=100),
        ),
    ]
